In [2]:
from transformers import TFBertModel
bert_model_name = 'bert-base-uncased'
bert_model = TFBertModel.from_pretrained(bert_model_name, use_safetensors=False)


Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [3]:
from transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained(bert_model_name)


In [4]:
sentence="play football"

tokens = bert_tokenizer.tokenize(sentence)

for token in tokens:
    token_id = bert_tokenizer.convert_tokens_to_ids(token)
    print(f"Token: {token}, Token ID: {token_id}")


Token: play, Token ID: 2377
Token: football, Token ID: 2374


In [5]:
sentence="play foottball"

tokens = bert_tokenizer.tokenize(sentence)

for token in tokens:
    token_id = bert_tokenizer.convert_tokens_to_ids(token)
    print(f"Token: {token}, Token ID: {token_id}")


Token: play, Token ID: 2377
Token: foot, Token ID: 3329
Token: ##t, Token ID: 2102
Token: ##ball, Token ID: 7384


In [6]:
sentence = "play football"

tokens_ids_tensor = bert_tokenizer(sentence, return_tensors='tf')
tokens_ids_tensor

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.


{'input_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 2377, 2374,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 1, 1, 1]], dtype=int32)>}

In [7]:
tokens_ids=tokens_ids_tensor['input_ids']
for i in range(len(tokens_ids)):
    print(f"Tokens: {tokens_ids[i]}")

Tokens: [ 101 2377 2374  102]


In [8]:
tokens_ids

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 2377, 2374,  102]], dtype=int32)>

In [9]:
tokens_ids.numpy()[0]

array([ 101, 2377, 2374,  102], dtype=int32)

In [10]:
tokens = bert_tokenizer.convert_ids_to_tokens(tokens_ids[0])
tokens

['[CLS]', 'play', 'football', '[SEP]']

In [11]:
outputs = bert_model(tokens_ids)
embeddings = outputs.last_hidden_state[0]
embeddings

<tf.Tensor: shape=(4, 768), dtype=float32, numpy=
array([[-0.06481667,  0.17851816, -0.7145612 , ..., -0.35007942,
         0.25353274, -0.1599989 ],
       [ 0.5689658 ,  0.38617215, -0.3798444 , ..., -0.04236888,
         0.8228664 , -0.5259888 ],
       [-0.87319154,  0.46801975, -0.45656395, ..., -0.6438818 ,
        -0.2901106 , -0.08834821],
       [ 0.9057377 ,  0.01548934, -0.3416377 , ...,  0.2333306 ,
        -0.48923424, -0.3333865 ]], shape=(4, 768), dtype=float32)>

In [12]:
len(embeddings[1])

768

In [13]:
embeddings[1]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([ 5.68965793e-01,  3.86172146e-01, -3.79844397e-01, -4.52961385e-01,
        2.74927288e-01,  1.52834266e-01,  5.20384848e-01,  2.33966947e-01,
        2.07015872e-01,  1.78359687e-01,  8.29816759e-02, -1.84635788e-01,
       -3.77842575e-01,  4.55170572e-01,  5.16449139e-02, -4.42378163e-01,
        5.02998590e-01,  7.01432765e-01,  2.00586855e-01,  1.17009771e+00,
       -4.70405608e-01,  2.55398333e-01, -1.42896026e-02,  4.87321913e-01,
        4.81782198e-01, -3.71673763e-01,  1.97453782e-01,  7.42846131e-01,
        4.55394760e-02, -1.24062717e-01,  2.77319729e-01,  1.12597696e-01,
        3.78180027e-01,  5.70604742e-01, -5.55267096e-01, -3.46157879e-01,
       -5.14118373e-01,  5.84963858e-01, -4.37439233e-01,  9.46320236e-01,
        7.19833449e-02, -1.76285371e-01, -8.70791152e-02,  4.50437993e-01,
       -2.37119257e-01, -3.04210126e-01,  2.13851050e-01, -4.02565002e-01,
        1.43626899e-01, -1.56308711e-03,  3.46378118

In [14]:
word = "play"
sentence1 = "I want to play football this morning"
sentence2 = "We are going to the theater to watch a play"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')
tokens_sentence1_ids=tokens_sentence1['input_ids'].numpy()[0]
tokens_sentence2_ids=tokens_sentence2['input_ids'].numpy()[0]
tokens_sentence1_ids,tokens_sentence2_ids

(array([ 101, 1045, 2215, 2000, 2377, 2374, 2023, 2851,  102], dtype=int32),
 array([ 101, 2057, 2024, 2183, 2000, 1996, 4258, 2000, 3422, 1037, 2377,
         102], dtype=int32))

In [15]:
word_id=bert_tokenizer.convert_tokens_to_ids(word)
word_id

2377

In [16]:
import numpy as np
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
word_token_index_sentence1,word_token_index_sentence2

(np.int64(4), np.int64(10))

In [17]:
outputs1 = bert_model(tokens_sentence1)
outputs2 = bert_model(tokens_sentence2)

embeddings_sentence1 = outputs1.last_hidden_state.numpy()[0]
embeddings_sentence2 = outputs2.last_hidden_state.numpy()[0]

embedding_word_sentence1 = embeddings_sentence1[word_token_index_sentence1]
embedding_word_sentence2 = embeddings_sentence2[word_token_index_sentence2]

from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity([embedding_word_sentence1], [embedding_word_sentence2])

print("Similarity score:", round(100*similarity_score[0][0],2))

Similarity score: 48.6


In [18]:
sentence1 = "I want to play football this morning"
sentence2 = "I play tennis with Jack today"
tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')
tokens_sentence1_ids=tokens_sentence1['input_ids'].numpy()[0]
tokens_sentence2_ids=tokens_sentence2['input_ids'].numpy()[0]
word_id=bert_tokenizer.convert_tokens_to_ids(word)
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
word_token_index_sentence1,word_token_index_sentence2
word_token_index_sentence1 = np.where(tokens_sentence1_ids == word_id)[0][0]
word_token_index_sentence2 = np.where(tokens_sentence2_ids == word_id)[0][0]
outputs1 = bert_model(tokens_sentence1)
outputs2 = bert_model(tokens_sentence2)

embeddings_sentence1 = outputs1.last_hidden_state.numpy()[0]
embeddings_sentence2 = outputs2.last_hidden_state.numpy()[0]

embedding_word_sentence1 = embeddings_sentence1[word_token_index_sentence1]
embedding_word_sentence2 = embeddings_sentence2[word_token_index_sentence2]

from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity([embedding_word_sentence1], [embedding_word_sentence2])

print("Similarity score:", round(100*similarity_score[0][0],2))



Similarity score: 77.29


In [20]:
sentence1 = "I love programming in Python"
sentence2 = "Python is a great programming language"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')

embeddings_sentence1 = bert_model(tokens_sentence1)['last_hidden_state']
embeddings_sentence2 = bert_model(tokens_sentence2)['last_hidden_state']

avg_embedding_sentence1 = np.mean(embeddings_sentence1, axis=1)
avg_embedding_sentence2 = np.mean(embeddings_sentence2, axis=1)

similarity_score = cosine_similarity(avg_embedding_sentence1, avg_embedding_sentence2)

print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score[0][0]), 2)}")

Cosine similarity between: 
'I love programming in Python' and 
'Python is a great programming language': 0.81


In [22]:
sentence1 = "I love programming in Python"
sentence2 = "The movie was very bad"

tokens_sentence1 = bert_tokenizer(sentence1, return_tensors='tf')
tokens_sentence2 = bert_tokenizer(sentence2, return_tensors='tf')

embeddings_sentence1 = bert_model(tokens_sentence1)['last_hidden_state']
embeddings_sentence2 = bert_model(tokens_sentence2)['last_hidden_state']

avg_embedding_sentence1 = np.mean(embeddings_sentence1, axis=1)
avg_embedding_sentence2 = np.mean(embeddings_sentence2, axis=1)

similarity_score = cosine_similarity(avg_embedding_sentence1, avg_embedding_sentence2)

print(f"Cosine similarity between: \n'{sentence1}' and \n'{sentence2}': {round(float(similarity_score[0][0]), 2)}")

Cosine similarity between: 
'I love programming in Python' and 
'The movie was very bad': 0.54
