In [6]:
from transformers import BertModel

In [7]:
from transformers import BertTokenizer

In [8]:
model_name = "bert-large-uncased"

In [9]:
model = BertModel.from_pretrained(model_name)

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

c:\Users\aziz1\OneDrive\Desktop\hsoub academy\ok\02_Google_Colab_Notebooks\.venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\aziz1\.cache\huggingface\hub\models--bert-large-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-large-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [10]:
tokenizer = BertTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [11]:
sentence1 = "I love programming"
sentence2 = "I enjoy coding"

In [17]:
tokens1 = tokenizer(sentence1, return_tensors="pt")
tokens2 = tokenizer(sentence2, return_tensors="pt")

In [18]:
import torch

with torch.no_grad():
    embeddings1 = model(**tokens1)["last_hidden_state"].numpy()
    embeddings2 = model(**tokens2)["last_hidden_state"].numpy()

embeddings1, embeddings2

(array([[[-0.08526063, -0.5764754 , -0.63337505, ..., -0.8695269 ,
          -0.6148906 ,  0.13499075],
         [-0.06757037, -0.57381445, -0.22566426, ..., -0.24722683,
          -0.14509901, -0.29641023],
         [-0.3467739 , -0.23050249, -0.0659056 , ..., -0.3864913 ,
           0.08854102,  0.0649807 ],
         [ 0.10635132, -0.15144303, -0.18361732, ...,  0.10190293,
          -0.76880264,  0.15373157],
         [-0.74198985, -0.22298789, -0.10586908, ..., -0.7624343 ,
          -0.56708395, -0.16787513]]], dtype=float32),
 array([[[-0.3766584 , -0.9046711 , -0.5042891 , ..., -0.9633738 ,
          -0.54231656,  0.11364973],
         [-0.0535457 , -0.5904749 , -0.40269813, ..., -0.15256305,
          -0.15487278, -0.2905526 ],
         [-0.21465814, -0.15130997, -0.21339577, ..., -0.333744  ,
           0.14532013, -0.32779938],
         [ 0.10372924,  0.06824342, -0.32612234, ...,  0.0596098 ,
          -0.720335  , -0.0162341 ],
         [-0.9849832 ,  0.22309393,  0.0861017

In [19]:
import numpy as np
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)
mean_embeddings1,mean_embeddings2

(array([[-0.22704868, -0.35104463, -0.24288626, ..., -0.4327553 ,
         -0.40146703, -0.02211647]], dtype=float32),
 array([[-0.30522323, -0.27102375, -0.27208072, ..., -0.4042992 ,
         -0.4078785 , -0.18755284]], dtype=float32))

In [20]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)
print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.92349565]]


In [22]:
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity

sentence1 = "I love programming"
sentence2 = "The movie is too bad"

# Use PyTorch tensors ("pt") instead of "tf"
tokens1 = tokenizer(sentence1, return_tensors="pt")
tokens2 = tokenizer(sentence2, return_tensors="pt")

# Pass inputs as **kwargs and convert PyTorch outputs to NumPy
with torch.no_grad():
    embeddings1 = model(**tokens1)["last_hidden_state"].numpy()
    embeddings2 = model(**tokens2)["last_hidden_state"].numpy()

# Calculate mean embeddings
mean_embeddings1 = np.mean(embeddings1, axis=1)
mean_embeddings2 = np.mean(embeddings2, axis=1)

# Compute cosine similarity
similarity = cosine_similarity(mean_embeddings1, mean_embeddings2)

print("Cosine Similarity:", similarity)

Cosine Similarity: [[0.3794226]]
