In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x4 = np.where(arr == 4)
print(x4)

for i in x4:
    print(arr[i])

(array([3, 5, 6]),)
[4 4 4]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [3]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [4]:
arr = np.array([3, 2, 0, 1])

ascending = np.sort(arr)

descending = ascending[::-1]
print(descending)

[3 2 1 0]


In [5]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [6]:
arr = np.array([41, 42, 43, 44])

filter_arr = [True, False, True, False]
newarr = arr[filter_arr]

print(newarr)

[41 43]


In [7]:
arr = np.array([41, 42, 43, 44])

filter_arr = []


for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
